# Generated by Django 5.2.3 on 2025-08-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('x_percent', models.DecimalField(decimal_places=2, help_text='Left position in % (0-100)', max_digits=5)),
                ('y_percent', models.DecimalField(decimal_places=2, help_text='Top position in % (0-100)', max_digits=5)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='poi_icons/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=128)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='core.destination')),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
            },
        ),
    ]
