# Generated by Django 5.2.3 on 2025-08-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_course_exam_courseapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseApplication',
        ),
    ]
