# Generated by Django 5.2.3 on 2025-08-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_blogpost_remove_courseapplication_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('tourism', 'Tourism & Hospitality'), ('guide', 'Tour Guide'), ('management', 'Tourism Management'), ('culture', 'Cultural Studies'), ('language', 'Language Courses'), ('photography', 'Travel Photography'), ('cooking', 'Local Cuisine'), ('crafts', 'Traditional Crafts')], default='tourism', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='Duration in weeks')),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('syllabus', models.TextField(blank=True, help_text='Course outline and topics covered')),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites and requirements')),
                ('benefits', models.TextField(blank=True, help_text='What students will gain from this course')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
