# Generated by Django 5.2.3 on 2025-08-20 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_courseapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('caravan_type', models.CharField(choices=[('luxury', 'Luxury Caravan'), ('adventure', 'Adventure Caravan'), ('family', 'Family Caravan'), ('eco', 'Eco-friendly Caravan'), ('compact', 'Compact Caravan'), ('premium', 'Premium Caravan')], default='family', max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('capacity', models.PositiveIntegerField(help_text='Number of people it can accommodate')),
                ('beds', models.PositiveIntegerField(default=2, help_text='Number of beds')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Air Conditioning')),
                ('has_kitchen', models.BooleanField(default=True, verbose_name='Kitchen')),
                ('has_bathroom', models.BooleanField(default=True, verbose_name='Bathroom')),
                ('has_generator', models.BooleanField(default=True, verbose_name='Generator')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='diesel', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('mileage', models.PositiveIntegerField(help_text='Average mileage per liter')),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rental rate', max_digits=10)),
                ('weekly_rate', models.DecimalField(decimal_places=2, help_text='Weekly rental rate (discounted)', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, help_text='Security deposit required', max_digits=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='caravans/')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='caravans/interior/')),
                ('exterior_image', models.ImageField(blank=True, null=True, upload_to='caravans/exterior/')),
                ('is_available', models.BooleanField(default=True)),
                ('pickup_locations', models.TextField(help_text='Available pickup locations')),
                ('max_distance', models.PositiveIntegerField(help_text='Maximum travel distance allowed (km)')),
                ('amenities', models.TextField(blank=True, help_text='Additional amenities and features')),
                ('rules', models.TextField(blank=True, help_text='Rental rules and restrictions')),
                ('insurance_info', models.TextField(blank=True, help_text='Insurance coverage details')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaravanBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=200)),
                ('return_location', models.CharField(blank=True, help_text='Leave blank if same as pickup', max_length=200)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('driving_license', models.CharField(help_text='Driving License Number', max_length=50)),
                ('destination', models.CharField(blank=True, help_text='Main destination for the trip', max_length=200)),
                ('purpose', models.CharField(blank=True, help_text='Purpose of trip (leisure, business, etc.)', max_length=100)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or requests')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.caravan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caravan_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
